name: 'Platformatic DB Deployer'
description: 'Deploy a Platformatic DB application to the cloud'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  platformatic_workspace_id:
    description: 'Platformatic workspace ID'
    required: true
  platformatic_workspace_key:
    description: 'Platformatic workspace key'
    required: true
  platformatic_project_path:
    description: 'Path to the Platformatic application project'
    required: false
  platformatic_config_path:
    description: 'Path to the Platformatic config file'
    required: false
  platformatic_env_path:
    description: 'Path to the Platformatic config file'
    required: false
  variables:
    description: 'Comma separated list of environment variables to be passed to the Platformatic application'
    required: false
  secrets:
    description: 'Comma separated list of environment secrets to be passed to the Platformatic application'
    required: false
  post_pr_comment:
    description: 'Configure whether comments with preview app URLs are posted on pull requests'
    required: false
    default: 'true'
outputs:
  deployment_id:
    description: 'Platformatic deployment ID'
  platformatic_app_url:
    description: 'URL of the deployed Platformatic DB application'
runs:
  using: 'node20'
  main: 'index.js'
